<?xml  version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN"   "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0" >
<!-- Generated via Iro -->
<dict>
  <key>fileTypes</key>
  <array> 
    <string>odot</string>
   </array>
  <key>name</key>
  <string>odot</string>
  <key>patterns</key>
  <array> 
    <dict>
      <key>include</key>
      <string>#main</string>
    </dict>
   </array>
  <key>scopeName</key>
  <string>source.odot</string>
  <key>uuid</key>
  <string></string>
  <key>repository</key>
  <dict>
    <key>main</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(\btrue\b|\bfalse\b|\bnil\b)</string>
          <key>name</key>
          <string>constant.language.odot</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(([\/a-zA-Z_][\/_a-zA-Z0-9]*\s*)+\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.odot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__1</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>entity.name.function.odot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\b[a-zA-Z_][_a-zA-Z0-9]*\b(?!\s*\())</string>
          <key>name</key>
          <string>variable.parameter.odot</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\()</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.odot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__2</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.odot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(/[a-zA-Z0-9_][_a-zA-Z0-9]*)</string>
          <key>name</key>
          <string>variable.odot</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#numeric</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\{)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.odot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__3</string>
            </dict>
           </array>
          <key>end</key>
          <string>(\})</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.odot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\&quot;)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.odot</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>text.odot</string>
          <key>end</key>
          <string>(\&quot;)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>punctuation.odot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(\[|\]|=|\.|\+|\-|\*|\:)</string>
          <key>name</key>
          <string>keyword.operator.odot</string>
        </dict>
        <dict>
          <key>match</key>
          <string>(,)</string>
          <key>name</key>
          <string>punctuation.odot</string>
        </dict>
        <dict>
          <key>include</key>
          <string>#multi_line_comment</string>
        </dict>
        <dict>
          <key>begin</key>
          <string>(\#.*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.odot</string>
            </dict>
          </dict>
          <key>patterns</key>
          <array> 
            <dict>
              <key>include</key>
              <string>#main__5</string>
            </dict>
           </array>
          <key>end</key>
          <string>(^(?=.{0,1})(?:|))</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>constant.language.odot</string>
            </dict>
          </dict>
        </dict>
        <dict>
          <key>match</key>
          <string>(//.*)</string>
          <key>name</key>
          <string>comment.odot</string>
        </dict>
        <dict>
          <key>match</key>
          <string>([^\s])</string>
          <key>name</key>
          <string>invalid.odot</string>
        </dict>
       </array>
    </dict>
    <key>main__1</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__2</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__3</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>main__4</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>main__5</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>include</key>
          <string>#main</string>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>begin</key>
          <string>(/\*)</string>
          <key>beginCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.odot</string>
            </dict>
          </dict>
          <key>contentName</key>
          <string>comment.odot</string>
          <key>end</key>
          <string>(\*/)</string>
          <key>endCaptures</key>
          <dict>
            <key>1</key>
            <dict>
              <key>name</key>
              <string>comment.odot</string>
            </dict>
          </dict>
        </dict>
       </array>
    </dict>
    <key>multi_line_comment__1</key>
    <dict>
      <key>patterns</key>
      <array> 
       </array>
    </dict>
    <key>numeric</key>
    <dict>
      <key>patterns</key>
      <array> 
        <dict>
          <key>match</key>
          <string>(-?([0-9]+|[0-9]*\.[0-9]+([eE][-\x{002b}]?[0-9]+)?))</string>
          <key>name</key>
          <string>constant.numeric.odot</string>
        </dict>
       </array>
    </dict>
  </dict>
</dict>
</plist>
